/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    3DTilesBIM: typeof import('./components/3DTilesBIM.vue')['default']
    BaseHeader: typeof import('./components/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/BaseSide.vue')['default']
    CameraTutorials: typeof import('./components/CameraTutorials.vue')['default']
    ClampToTerrain: typeof import('./components/ClampToTerrain.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModelColorConfig: typeof import('./components/ModelColorConfig.vue')['default']
    ModelSelector: typeof import('./components/ModelSelector.vue')['default']
    ThreeDTilesBIM: typeof import('./components/threeDTilesBIM.vue')['default']
  }
}
